---
- name: Run artisan optimize
  command: php artisan optimize
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  become: true
  become_flags: '-iS'

- name: Create config cache
  command: php artisan config:cache
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  become: true
  become_flags: '-iS'

- name: Finalize the deploy
  deploy_helper:
    current_path: "{{ project_current_path }}"
    path: "{{ project_root }}"
    release: "{{ deploy_helper.new_release }}"
    state: finalize
  become: true
  become_flags: '-iS'

- debug:
    msg: "{{ project_version }}@{{ git_clone.after | truncate(7, True, '') }} deployed as release {{ deploy_helper.new_release }}"
