---
- name: Run artisan optimize
  command: php artisan optimize
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Create config cache
  command: php artisan config:cache
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Change group ownership of storage
  file:
    path: "{{ deploy_helper.new_release_path }}/storage"
    group: www-data
    mode: 0755
  become: true
  become_user: root
  become_method: sudo

- name: Finalize the deploy
  deploy_helper:
    current_path: "{{ project_current_path }}"
    path: "{{ project_root }}"
    release: "{{ deploy_helper.new_release }}"
    state: finalize

- debug:
    msg: "{{ project_version }}@{{ git_clone.after | truncate(7, True, '') }} deployed as release {{ deploy_helper.new_release }}"
