---
- name: write unfinished file
  file:
    path: "{{ project_source_path }}/{{ deploy_helper.unfinished_filename }}"
    state: touch
  become: true
  become_flags: '-iS'

- name: Create new release dir
  file:
    path: "{{ deploy_helper.new_release_path }}"
    state: directory
  become: true
  become_flags: '-iS'

- name: Run git archive to populate new build dir
  shell: git archive {{ project_version }} | tar xf - -C {{ deploy_helper.new_release_path }}
  args:
    chdir: "{{ project_source_path }}"
  become: true
  become_flags: '-iS'
