---
- name: Create remote tmp build directory
  tempfile:
    state: directory
    suffix: "{{site}}"
  register: remote_build

- name: Make remote tmp build directory readable
  file:
    path: "{{ remote_build.path }}"
    mode: 0777

- name: Copy project assets to remote tmp
  synchronize:
    src: "{{ local_build.path }}/public"
    dest: "{{ remote_build.path }}"
    group: no
    owner: no
    rsync_opts: --chmod=Du=rwx,--chmod=Dg=rwx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=rw,--chmod=Fo=rw

- name: Copy project assets from tmp to project directory
  synchronize:
    src: "{{ remote_build.path }}/public"
    dest: "{{ deploy_helper.new_release_path }}"
    group: no
    owner: no
    rsync_opts: --chmod=Du=rwx,--chmod=Dg=rwx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=rw,--chmod=Fo=r
  delegate_to: "{{ inventory_hostname }}"

- name: Cleanup remote tmp build files
  file:
    state: absent
    path: "{{ remote_build.path }}"

- name: Cleanup local build files
  connection: local
  file:
    state: absent
    path: "{{ local_build.path }}"
