---
- name: Check for composer.json in project root or project_subtree_path
  stat:
    path: "{{ deploy_helper.new_release_path }}/composer.json"
  register: composer_json

- name: Fail if composer.json not found
  fail:
    msg: "Unable to find a `composer.json` file in the root of '{{ deploy_helper.new_release_path }}'. Make sure your repo has a `composer.json` file in its root or edit `repo_subtree_path` for '{{ site }}' in `wordpress_sites.yml` so it points to the directory with a `composer.json` file."
  when: not composer_json.stat.exists

- name: Install Composer dependencies
  command: composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader
  args:
    chdir: "{{ deploy_helper.new_release_path }}"

- name: Ensure directories are 0775
  command: find {{ deploy_helper.new_release_path }} -type d -exec chmod 0775 {} \;

- name: Ensure files are 0664
  command: find {{ deploy_helper.new_release_path }} -type f -exec chmod 0664 {} \;

- name: Create remote tmp build directory
  tempfile:
    state: directory
    suffix: "{{project.theme}}"
  register: remote_build

- name: Make remote tmp build directory readable
  file:
    path: "{{ remote_build.path }}"
    mode: 0777

- name: Copy project assets to remote tmp
  synchronize:
    src: "{{ local_build.path }}/dist"
    dest: "{{ remote_build.path }}"
    group: no
    owner: no
    rsync_opts: --chmod=Du=rwx,--chmod=Dg=rwx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=rw,--chmod=Fo=rw

- name: Copy project assets from tmp to project directory
  synchronize:
    src: "{{ remote_build.path }}/dist"
    dest: "{{ deploy_helper.new_release_path }}"
    group: no
    owner: no
    rsync_opts: --chmod=Du=rwx,--chmod=Dg=rwx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=rw,--chmod=Fo=r
  delegate_to: "{{ inventory_hostname }}"

- name: Cleanup remote tmp build files
  file:
    state: absent
    path: "{{ remote_build.path }}"

- name: Cleanup local build files
  connection: local
  file:
    state: absent
    path: "{{ local_build.path }}"
